# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup packages
        run: npm ci

#     - name: Build for Windows
#       run: npm run build:win

#     - name: Build for mac(intel)
#       run: npm run build:osx

      - name: Build for mac(arm)
        run: npm run build:mas

#     - name: Upload Windows artifacts
#       uses: actions/upload-artifact@v3.1.1
#       with:
#         name: windows_artifact
#         path: release_win
          
#     - name: Upload mac(intel) artifacts
#       uses: actions/upload-artifact@v3.1.1
#       with:
#         name: mac_intel_artifact
#         path: release_osx
          
      - name: Upload mac(arm) artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: mac_arm_artifact
          path: release_mas
